name: After merge
on:
  pull_request:
    branches: [ master ]
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  masterDeploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v2
        - name: Configure JDK
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Build
          run: ./gradlew app:assembleDebug
        - name: Upload apk to Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1
          with:
            appId: ${{secrets.FIREBASE_SERVICE_ACCOUNT_EDUCATION_2B3AC}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT}}
            groups: testers
            file: app/build/outputs/apk/debug/app-debug.apk
            releaseNotes: "Text of debug apk in master"
        - name: Upload artefact to App Center
          uses: wzieba/AppCenter-Github-Action@v1
          with:
            appName: FeskovaKseniia/Education
            token: ${{secrets.APP_CENTER}}
            group: Collaborators
            file: app/build/outputs/apk/debug/app-debug.apk
            releaseNotes: "Text of debug apk in master"
