name: For develop
on:
    pull_request:
      branches: [develop,master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
              # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Build Apk
        run: ./gradlew :app:assembleDebug
      - name: Delivery to AppCenter
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install
      - name: publish dev apk to App Center
        run: npm install -g appcenter-cli appcenter distribute release --app "Education-App" --file app/build/outputs/apk/debug/app-debug.apk --token "b9b0f3dc25b91edbcd33aa27b482dbf4803a97ad" --group "Collaborators"

#      - run: appcenter distribute release --file app/build/outputs/apk/debug/app-debug.apk --token "b9b0f3dc25b91edbcd33aa27b482dbf4803a97ad"
