name: For develop
on:
  pull_request:
    branches: [ develop,master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew app:assembleDebug
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'ref/heads/develop' }}
  steps:
      - uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_SERVICE_ACCOUNT_EDUCATION_2B3AC}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
