name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: output the string
        run: echo "Hello world"
      - name: set up multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print
          (platform.processor())
        shell: python